# Generated by Django 4.2.7 on 2023-12-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libraryapp', '0003_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
